name: Generate terraform docs
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Render terraform docs and push changes back
      uses: terraform-docs/gh-actions@main
      with:
        config-file: .terraform-docs.yml
        working-dir: .
        recursive: true
        recursive-path: .
        output-file: README.md
        output-method: inject
        git-push: "true"